name: Deploy Registration Form

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Deploy (Simulation)
        run: |
          echo "Running Build Simulation..."
          echo "No build step required for HTML/CSS/JS projects."

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: .
